### ISSUE TITLE
Can't seem to get the compiled .exe to work

### ISSUE THREAD

**Issue by DandelionSprout** [wwalexander/hostsblock#1]
Greetings from the maintainer of a Norwegian adblock list, who am curious about this conversion tool that you've made.

After spending some time on learning how to get Cygwin to compile an .exe from the source code, the .exe seems to just close itself after ⅒ of a second each time I try to run it. And the _hostsblock list_ command doesn't seem to be found by Cygwin or by Windows' command line either.

I use Windows 10 Fall Creators Edition, and I compiled the .exe from a folder that contained all of this repository's files. So is there something I'm doing wrong, or is there an issue in the code? It's probably the former, I admit, but I'm going to need help with this nevertheless.

**Comment by wwalexander** [comment]
Are you running the .exe from the command line when it closes itself?

**Comment by DandelionSprout** [comment]
Initially no, but I later realised that it was meant to be run through the command line.

I did make a fair degree of progress since my original comment, and after much trial and error discovered that the command ( _hostsblock list_ ) that was listed in the Readme was completely wrong, and that it was meant to be run as _./hostsblock [name of the list-file]_ instead.

However, running a _./hostsblock [name of the list-file]_ command (in this case _./hostsblock JohnMadden.txt_, since I often use "John Madden" as a generic title for my files) now seems to give empty feedback, and I can't find the output file anywhere.
![image](https://user-images.githubusercontent.com/22780683/36978446-cc95f6c2-2084-11e8-8c85-f9e9d37c8bed.png)

Does this mean that the script has been run or not? And if yes, where's the default output folder (or does it rely on the _Nano Editor_ text render thing that I haven't installed yet)?

**Comment by wwalexander** [comment]
> I did make a fair degree of progress since my original comment, and after much trial and error discovered that the command ( hostsblock list ) that was listed in the Readme was completely wrong, and that it was meant to be run as ./hostsblock [name of the list-file] instead.

My mistake: the "list" in the example command is meant to be a stand-in for the name of the filterlist file you want to convert. I will update the documentation to make this more clear.

I use `hostsblock` instead of `./hostsblock` in my usage examples because I do not want to assume how people will run my program. They may set up their [PATH variable](https://en.wikipedia.org/wiki/PATH_(variable)) to run the program from anywhere on the command line; they may run it locally from the build directory as you have, etc. If you wish to run the program exactly as in my examples, you will need to copy the executable somewhere.

> However, running a ./hostsblock [name of the list-file] command (in this case ./hostsblock JohnMadden.txt, since I often use "John Madden" as a generic title for my files) now seems to give empty feedback

Does JohnMadden.txt contain AdBlock Plus filterlist rules? If JohnMadden.txt is a blank file, then hostsblock will not have any output, as there are no rules to convert. Also, please be aware that this tool only converts very basic rules that translate easily to hosts entries, so even if your file contains some rules, they may not be output into hosts entries. Refer to the README for more info.

> and I can't find the output file anywhere.

Like many command-line tools, hostsblock prints its output to the terminal. If you wish to save the entries to a file in Cygwin, you can [redirect the output to a file](https://en.wikipedia.org/wiki/Redirection_(computing)#Redirecting_standard_input_and_standard_output). Again, refer to the README for some useful examples.

**Comment by wwalexander** [comment]
3ad36ee adds brackets around the argument in the usage example and names it a little more clearly.

**Comment by DandelionSprout** [comment]
Ah, thanks for all the clarifications and tips. I eventually ended up trying out the command _curl https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ExperimentalNorwegianList.txt | ./hostsblock - > JohnMadden2.txt_ (with JohnMadden2.txt being a file I created specifically to serve as an output destination), after I had installed Cygwin's _curl_ package, and it finally worked! 🎉 

>Also, please be aware that this tool only converts very basic rules that translate easily to hosts entries, (...)

...ah. I suppose that explains why the successful output only contained ten entries out of [an original ca. 475](https://github.com/DandelionSprout/adfilt/blob/master/ExperimentalNorwegianList.txt):

_127.0.0.1  adext.inkclub.com
127.0.0.1	ads.terrengsykkel.no
127.0.0.1	adserver.digitoday.com
127.0.0.1	banner.finn.no
127.0.0.1	easy-ad.no
127.0.0.1	emerio.no
127.0.0.1	primetime.ad.primetime.net
127.0.0.1	server-no.imrworldwide.com
127.0.0.1	server-us.imrworldwide.com
127.0.0.1	static.itrack.it_

I was originally hoping that perhaps 150 entries would've made the cut, since ca. 160 entries had || in front of them. However, it's not the biggest loss ever, since I ended up following a different advice I got elsewhere yesterday, which was to use Excel to add 127.0.0.1 in front of all entries and remove the || characters, and then [save it as a text file](https://github.com/DandelionSprout/adfilt/blob/master/NorwegianExperimentalList%20alternate%20versions/hosts). The syntax is probably very wonky in regards to PCs and routers, but uBlock Origin didn't seem to complain about them.

Though I was a fair bit confused by your tool to begin with, this has been a rewarding experience for me when it came to learning about command line environments, since I've previously been a GUI-or-bust kind of person, and for that I thank you.

**Comment by wwalexander** [comment]
> I was originally hoping that perhaps 150 entries would've made the cut, since ca. 160 entries had || in front of them. However, it's not the biggest loss ever, since I ended up following a different advice I got elsewhere yesterday, which was to use Excel to add 127.0.0.1 in front of all entries and remove the || characters, and then save it as a text file.

Unfortunately, many of the rules in that list have special syntax that is meant to block only specific pages or HTML elements of pages on websites. The hosts file can only block on the level of domain names. If you simply extract the domain name from these special rules, you will block things you aren't meant to (the rules have the special syntax specifically so that they only block the right things). You can give it a shot, but I'd rather that my program does not create false positives and potentially break when given a list that works fine via an ABP-compatible ad blocker. If you're able to find a way to avoid this issue while capturing more rules, I would welcome contributors!

> Though I was a fair bit confused by your tool to begin with, this has been a rewarding experience for me when it came to learning about command line environments, since I've previously been a GUI-or-bust kind of person, and for that I thank you.

Happy to help! I'll try to throw up a native Windows build on the Releases page.
