### ISSUE TITLE
Tool usage

### ISSUE THREAD

**Issue by dracuking** [wwalexander/hostsblock#2]
Not sure how to use this tool. I downloaded the hostsblock.exe windows-amd64 release. Launched it and got a blank command prompt. Open hostsblock.exe via windows command prompt, copied and paste hostsblock curl -s https://www.fanboy.co.nz/r/fanboy-ultimate.txt | hostsblock -. all i get back is: usage: hostsblock [filterlist]. Can you please help? Im using Windows 10

**Comment by wwalexander** [comment]
To use the pipe (`|`) syntax, you'll need to run the command from PowerShell instead of Command Prompt. Note that the examples with pipes are simply meant to show convenient one-line methods of generating the hosts file. If you don't want to bother, you could just open https://www.fanboy.co.nz/r/fanboy-ultimate.txt in your web browser, save it to your computer (e.g. C:\Users\eldervamp\Desktop\fanboy-ultimate.txt), and then run the command directly on the file (e.g. `hostsblock "C:\Users\eldervamp\Desktop\fanboy-ultimate.txt"`). You will need to adjust the command depending on where you save the filter list file. And of course, you will need to copy the output of the command into your hosts file for it to have any effect.
